### ISSUE TITLE
Incorrect bijector for heterogeneous Product distribution

### ISSUE THREAD

**Issue by bgroenks96** [TuringLang/Bijectors.jl#290]
As noted in the [code](https://github.com/TuringLang/Bijectors.jl/blob/04b79dd46eca8cea2f988348c47bd5e720a2b9a4/src/transformed_distribution.jl#L75), the implementation of `bijector` for heterogeneous product distributions doesn't make sense. Why is not just `Stacked(map(bijector, d.v))`?

Here is my fixed version:
```julia
function Bijectors.bijector(prod::Product{Continuous})
    D = eltype(prod.v)
    return if Bijectors.has_constant_bijector(D)
        Bijectors.elementwise(bijector(prod.v[1]))
    else
        Bijectors.Stacked(map(bijector, Tuple(prod.v)))
    end
end
```

**Comment by torfjelde** [comment]
I believe I did this because the previous version was using the `TruncatedBijector` and so I didn't want to touch in the PR where I added `has_constant_bijector`, etc.

The downside with the `map` approach is that it will be much slower vs. vectorized `TruncatedBijector` (and `UnivariateDistribution` should be implementing the `minimum` and `maximum` anyways, no?)

**Comment by bgroenks96** [comment]
I can check again, but I don't think it works when the array of distributions is heterogeneous.

**Comment by bgroenks96** [comment]
Ok, it actually seems to work... I can't reproduce the behavior I saw before. I'll just assume I did something wrong!
