### ISSUE TITLE
Better fallback for inversion/logpdf

### ISSUE THREAD

**Issue by theogf** [TuringLang/Bijectors.jl#56]
Right now the behavior when `Roots.find_zero()` (particularly with `PlanarLayer` and `RadialLayer`) fails is to stop everything. It would be nice to have a helper message on what to correct/improve to make the model more stable or to have a fallback which makes approximations but is more stable!

**Comment by devmotion** [comment]
This is resolved, `RadialLayer` does use the closed-form expression and in the latest version the root finding algorithm for the inverse of `PlanarLayer` should converge very fast due to an improved initial bracket and is very accurate (see the code for details). A warning message is printed if it fails to converge.
